"""Initial model

Revision ID: bf8a1f9a08ad
Revises: 
Create Date: 2025-02-27 14:08:59.064999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8a1f9a08ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dbuser_username', table_name='dbuser')
    op.drop_table('dbuser')
    op.drop_index('ix_dbcollection_name', table_name='dbcollection')
    op.drop_table('dbcollection')
    op.drop_index('ix_dborg_name', table_name='dborg')
    op.drop_table('dborg')
    op.drop_index('ix_dbresource_name', table_name='dbresource')
    op.drop_table('dbresource')
    op.drop_index('ix_dbgroup_name', table_name='dbgroup')
    op.drop_table('dbgroup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dbgroup',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dbgroup_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['dbcollection.id'], name='dbgroup_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dbgroup_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_dbgroup_name', 'dbgroup', ['name'], unique=False)
    op.create_table('dbresource',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['dbgroup.id'], name='dbresource_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dbresource_pkey')
    )
    op.create_index('ix_dbresource_name', 'dbresource', ['name'], unique=False)
    op.create_table('dborg',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dborg_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dborg_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_dborg_name', 'dborg', ['name'], unique=False)
    op.create_table('dbcollection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dbcollection_pkey')
    )
    op.create_index('ix_dbcollection_name', 'dbcollection', ['name'], unique=False)
    op.create_table('dbuser',
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['dborg.id'], name='dbuser_org_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dbuser_pkey')
    )
    op.create_index('ix_dbuser_username', 'dbuser', ['username'], unique=False)
    # ### end Alembic commands ###
